### ISSUE TITLE
[FR] 实体列表添加搜索和排序功能

### ISSUE THREAD

**Issue by KagaJiankui** [daimiaopeng/home-assistant-TrafficMonitor#1]
能否在插件配置页面实现简单的实体列表按字母排序和按ID搜索功能? 实体数量一多, 一个一个找不太方便

**Comment by daimiaopeng** [comment]
> 能否在插件配置页面实现简单的实体列表按字母排序和按ID搜索功能? 实体数量一多, 一个一个找不太方便

这个我有时间改一下

**Comment by daimiaopeng** [comment]
> 能否在插件配置页面实现简单的实体列表按字母排序和按ID搜索功能? 实体数量一多, 一个一个找不太方便

其实你也可以在配置文件(和插件dll同个目录）里面直接添加，第一个就是格式为：实体id;实体id;

**Comment by daimiaopeng** [comment]
> > 能否在插件配置页面实现简单的实体列表按字母排序和按ID搜索功能? 实体数量一多, 一个一个找不太方便
> 
> 其实你也可以在配置文件(和插件dll同个目录）里面直接添加，第一个就是格式为：实体id;实体id;

手动复制Parent entity ID到配置文件里面`;`分割TrafficMonitor\plugins\homeAssistant.ini
![image](https://github.com/daimiaopeng/home-assistant-TrafficMonitor/assets/32475719/fe4d6a70-5518-4a0d-9abf-2f126937c819)

```
[config]
entity_id_list=sensor.miaomiaoce_t2_2ff1_relative_humidity;sensor.miaomiaoce_t2_2ff1_temperature_humidity_sensor;sensor.miaomiaoce_t2_c220_relative_humidity;sensor.miaomiaoce_t2_c220_temperature_humidity_sensor;
token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIyZGE0YzU3NGEyNjM0MDQ5OTczYTRiNTM2YThmYTU2OCIsImlhdCI6MTY5OTQxMTk2NSwiZXhwIjoyMDE0NzcxOTY1fQ.8mWwDoD7e06DEYQrgMfS6YuG2iZB7Q540_yLL96Rfb4
url=http://localhost:8886

```
