### ISSUE TITLE
勾选多个Devices，显示设置只有一个

### ISSUE THREAD

**Issue by Zrincet** [daimiaopeng/home-assistant-TrafficMonitor#2]
![image](https://github.com/daimiaopeng/home-assistant-TrafficMonitor/assets/11169330/d156498e-0978-4bfe-9b88-b40b185e63e3)

![image](https://github.com/daimiaopeng/home-assistant-TrafficMonitor/assets/11169330/520396c0-7a14-4a39-af0e-2be0eee5a8ba)

当勾选多个Devices时，显示设置只有一个Device

**Comment by daimiaopeng** [comment]
看一看插件目录下面的配置文件entity_id_list是不是有两个id，有的话重启软件，再在显示里面瞧瞧是不是有两个设备
TrafficMonitor\plugins\homeAssistant.ini
```
[config]
entity_id_list=sensor.miaomiaoce_t2_2ff1_relative_humidity;sensor.miaomiaoce_t2_2ff1_temperature_humidity_sensor;sensor.miaomiaoce_t2_c220_relative_humidity;sensor.miaomiaoce_t2_c220_temperature_humidity_sensor;
token=XXX
url=http://localhost:8886

```

**Comment by Zrincet** [comment]
@daimiaopeng 感谢，配置文件中是有2个，重启之后生效了，在重启之前是只有一个。
